services:
    nginx:
        build:
            context: support/docker/containers/nginx
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        container_name: ${PROJECT_NAME}-nginx
        ports:
            - "8080:80"

    php_fpm:
        build: 'support/docker/containers/php-fpm'
        volumes:
            - ./:/app
        container_name: ${PROJECT_NAME}-php-fpm
        depends_on:
            - mysql
        ports:
            - '9000:9000'

    php-cli:
        build: 'support/docker/containers/php-cli'
        volumes:
            - ./:/app
        container_name: ${PROJECT_NAME}-php-cli
        environment:
            - APP_ENV=${API_APP_ENV}
            - APP_DEBUG=${API_APP_DEBUG}
            - APP_SECRET=${API_APP_SECRET}

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql:/var/lib/mysql
        container_name: ${PROJECT_NAME}-mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"

volumes:
    mysql:

networks:
    iphotonic_network:
        driver: bridge