services:
    nginx:
        build: 'support/docker/containers/nginx'
        container_name: ${PROJECT_NAME}-nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - './:/var/www/app'
            - '${SSL_CERT}:/etc/nginx/ssl/fullchain.pem'
            - '${SSL_PRIVATE_KEY}:/etc/nginx/ssl/privkey.pem'
        networks:
            - iphotonic_network
        environment:
            - DOMAIN=${DOCKER_DOMAIN}
        depends_on:
            - php_fpm

    php_fpm:
        build: 'support/docker/containers/php-fpm'
        volumes:
            - ./:/var/www/app
        container_name: ${PROJECT_NAME}-php-fpm
        depends_on:
            - mysql
        ports:
            - 9000:9000
        networks:
            - iphotonic_network

    php-cli:
        build: 'support/docker/containers/php-cli'
        volumes:
            - ./:/var/www/app
        container_name: ${PROJECT_NAME}-php-cli
        environment:
            - APP_ENV=${APP_ENV}
            - APP_DEBUG=${APP_DEBUG}
            - APP_SECRET=${APP_SECRET}
        networks:
            - iphotonic_network

    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql:/var/lib/mysql
        container_name: ${PROJECT_NAME}-mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
            - "MYSQL_DATABASE=${MYSQL_DATABASE}"
            - "MYSQL_USER=${MYSQL_USER}"
            - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        networks:
            - iphotonic_network

volumes:
    mysql:

networks:
    iphotonic_network:
        driver: bridge